Indexer
thebayesianconspiracy/scanpix pull request #10
Opened 2022-06-23 09:29 UTC by TheCodeYoda

Service to detect changes in directory and index automatically

2022-06-29 15:07 UTC, sam17 approved these changes

2022-06-29 15:15 UTC, sam17 requested changes
Can you make user select dirctories and store it? And then show indexing progress?

2022-07-10 12:26 UTC, sam17 approved these changes

2022-07-10 13:58 UTC, TheCodeYoda commented
Auto indexes images added and deleted

2022-07-10 13:59 UTC, merged