Hotfix indexer
thebayesianconspiracy/scanpix pull request #29
Opened 2022-07-14 11:29 UTC by TheCodeYoda

- [x] made Indexer singleton
- [x] indexing already existing files which were not indexed 
- [x] proper error handling for file extensions other than images

2022-07-15 09:37 UTC, sam17 requested changes
I really think indexer needs to have tests. 

For eg. dummy directory with files to be checked if indexed or not and negative cases handled.

2022-07-25 09:01 UTC, sam17 requested changes

2022-07-25 09:01 UTC, sam17 commented on worker/watch_and_index.py
>  class MyHandler(FileSystemEventHandler):
Why is this called `MyHandler`?

2022-07-25 09:26 UTC, TheCodeYoda commented on docker-compose.yml
> +      - index
this is needed to bring the scanpix server and the indexer up easily for debugging

2022-07-26 13:56 UTC, sam17 approved these changes

2022-07-26 13:56 UTC, merged